### PR TITLE
Add function to load image from array2d data

### PR DESCRIPTION
**Pull request by yuzifu**

### CODE REVIEW

**Comment by takuya-takeuchi** [comment]
Thank you for your contributions.

But I'm unable to make a decision to merge it.
Because

* The user has to get conscious about DlibDotNet types
  * FaceRecognitionDotNet depends on them but encapsulate them. Eg. Image and FaceEncoding class
  * In the first place, I did not make internal Image and FaceEncoding class if I don't care about it.

**Comment by takuya-takeuchi** [comment]
I consider to add new overload which accept byte[] array.

* MUST add new overload for Matrix<RgbPixel>(byte[] array...)
  * And add ToArray method which returns  byte[] for Array2D<RgbPixel> and etc

**Comment by edwinckc** [comment]
Haha, thank you so much for porting Dlib and even creating a FaceNet implementation! =D

About my own use case... currently I require 4 steps to use a SoftwareBitmap:
1. Copy SoftwareBitmap (in RGBA8 format) to byte array. (built-in conversion doesn't include RGB8 format)
2. Manually convert to RGB8 byte array.
3. Use Dlib.LoadImageData<RgbPixel> to get an Array2D object.
4. LoadImageData using the method described in this PR.

Specifically supporting SoftwareBitmaps may be too much, but I think having a method to load image data from a byte array (in RGB8 format) would allow much more to be done using this library. The user doesn't have to know about Dlib's Array2D type, but can still make use of FaceRecognition's ability to process images/frames in memory. Of course, this proposal would actually mean not adding the _LoadImageData(Array2D<RgbPixel>)_ method, which would be counter to this PR.

Would be interesting to know @yuzifu's use case, which may warrant adding a load method for Array2D.

**Comment by takuya-takeuchi** [comment]
Hi, everyone.

I added Matrix<T>(byte[] array...) constructor and Array2D<T>.ToBytes method for DlibDotNet. Then I added FaceRecognition.LoadImage(byte[] array..) method.
It does not convert directly Array2D<T> to Image class, but it could satisfy general needs.

Please check out

* https://www.nuget.org/packages/FaceRecognitionDotNet/1.2.3.4
* https://www.nuget.org/packages/FaceRecognitionDotNet-WithCUDA/1.2.3.4

**Comment by yuzifu** [comment]
The reason I added this function is that I use OpenCVSharp3 to get the image from the webcam, it is Mat type, and FRDotNet's FaceCompare only accepts the Image type, so I need find a way to convert the Mat type to the Image type.

**Comment by takuya-takeuchi** [comment]
Currently, FR supports to create Image from byte array.
So it can satisfy this PR.

**Pull request closed without merging**
